--
-- Table structure for table `Countries`
--

CREATE TABLE IF NOT EXISTS `Countries` (
  `id_country` int(11) NOT NULL AUTO_INCREMENT,
  `countryName` varchar(25) DEFAULT NULL,
  `IsoCode` varchar(2) DEFAULT NULL,
  `icon` varchar(6) DEFAULT NULL,
  PRIMARY KEY (`id_country`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=166 ;

--
-- Dumping data for table `Countries`
--

INSERT INTO `Countries` VALUES(1, 'Afghanistan', 'af', 'af.png');
INSERT INTO `Countries` VALUES(2, 'Albania', 'al', 'al.png');
INSERT INTO `Countries` VALUES(3, 'Algeria', 'dz', 'dz.png');
INSERT INTO `Countries` VALUES(4, 'Andorra', 'ad', 'ad.png');
INSERT INTO `Countries` VALUES(5, 'Anguilla', 'ai', 'ai.png');
INSERT INTO `Countries` VALUES(6, 'Antigua - Barbuda', 'ag', 'ag.png');
INSERT INTO `Countries` VALUES(7, 'Argentina', 'ar', 'ar.png');
INSERT INTO `Countries` VALUES(8, 'Armenia', 'am', 'am.png');
INSERT INTO `Countries` VALUES(9, 'Aruba', 'aw', 'aw.png');
INSERT INTO `Countries` VALUES(10, 'Australia', 'au', 'au.png');
INSERT INTO `Countries` VALUES(11, 'Azerbaijan', 'az', 'az.png');
INSERT INTO `Countries` VALUES(12, 'Bahamas', 'bs', 'bs.png');
INSERT INTO `Countries` VALUES(13, 'Bahrain', 'bh', 'bh.png');
INSERT INTO `Countries` VALUES(14, 'Bangladesh', 'bd', 'bd.png');
INSERT INTO `Countries` VALUES(15, 'Barbados', 'bb', 'bb.png');
INSERT INTO `Countries` VALUES(16, 'Belarus', 'by', 'by.png');
INSERT INTO `Countries` VALUES(17, 'Belgium', 'be', 'be.png');
INSERT INTO `Countries` VALUES(18, 'Belize', 'bz', 'bz.png');
INSERT INTO `Countries` VALUES(19, 'Benin', 'bj', 'bj.png');
INSERT INTO `Countries` VALUES(20, 'Bermuda', 'bm', 'bm.png');
INSERT INTO `Countries` VALUES(21, 'Bhutan', 'bt', 'bt.png');
INSERT INTO `Countries` VALUES(22, 'Bolivia', 'bo', 'bo.png');
INSERT INTO `Countries` VALUES(23, 'Bosnia', 'ba', 'ba.png');
INSERT INTO `Countries` VALUES(24, 'Botswana', 'bw', 'bw.png');
INSERT INTO `Countries` VALUES(25, 'Brazil', 'br', 'br.png');
INSERT INTO `Countries` VALUES(26, 'Brunei', 'bn', 'bn.png');
INSERT INTO `Countries` VALUES(27, 'Bulgaria', 'bg', 'bg.png');
INSERT INTO `Countries` VALUES(28, 'Burkina Faso', 'bf', 'bf.png');
INSERT INTO `Countries` VALUES(29, 'Burundi', 'bi', 'bi.png');
INSERT INTO `Countries` VALUES(30, 'Cambodia', 'kh', 'kh.png');
INSERT INTO `Countries` VALUES(31, 'Cameroon', 'cm', 'cm.png');
INSERT INTO `Countries` VALUES(32, 'Canada', 'ca', 'ca.png');
INSERT INTO `Countries` VALUES(33, 'Cape Verde', 'cv', 'cv.png');
INSERT INTO `Countries` VALUES(34, 'Central Africa Republic', 'cf', 'cf.png');
INSERT INTO `Countries` VALUES(35, 'Chad', 'td', 'td.png');
INSERT INTO `Countries` VALUES(36, 'Chile', 'cl', 'cl.png');
INSERT INTO `Countries` VALUES(37, 'Christmas Island', 'ci', 'ci.png');
INSERT INTO `Countries` VALUES(38, 'China', 'cn', 'cn.png');
INSERT INTO `Countries` VALUES(39, 'Colombia', 'co', 'co.png');
INSERT INTO `Countries` VALUES(40, 'Congo', 'cg', 'cg.png');
INSERT INTO `Countries` VALUES(41, 'Cook Islands', 'ck', 'ck.png');
INSERT INTO `Countries` VALUES(42, 'Costa Rica', 'cr', 'cr.png');
INSERT INTO `Countries` VALUES(43, 'Cote D''Ivoire', 'ct', 'ct.png');
INSERT INTO `Countries` VALUES(44, 'Croatia', 'hr', 'hr.png');
INSERT INTO `Countries` VALUES(45, 'Cuba', 'cu', 'cu.png');
INSERT INTO `Countries` VALUES(46, 'Curacao', 'cb', 'cb.png');
INSERT INTO `Countries` VALUES(47, 'Cyprus', 'cy', 'cy.png');
INSERT INTO `Countries` VALUES(48, 'Czech Republic', 'cz', 'cz.png');
INSERT INTO `Countries` VALUES(49, 'Denmark', 'dk', 'dk.png');
INSERT INTO `Countries` VALUES(50, 'Djibouti', 'dj', 'dj.png');
INSERT INTO `Countries` VALUES(51, 'Dominica', 'dm', 'dm.png');
INSERT INTO `Countries` VALUES(52, 'Dominican Republic', 'do', 'do.png');
INSERT INTO `Countries` VALUES(53, 'Ecuador', 'ec', 'ec.png');
INSERT INTO `Countries` VALUES(54, 'Egypt', 'eg', 'eg.png');
INSERT INTO `Countries` VALUES(55, 'El Salvador', 'sv', 'sv.png');
INSERT INTO `Countries` VALUES(56, 'Equatorial Guinea', 'gq', 'gq.png');
INSERT INTO `Countries` VALUES(57, 'Eritrea', 'er', 'er.png');
INSERT INTO `Countries` VALUES(58, 'Estonia', 'ee', 'ee.png');
INSERT INTO `Countries` VALUES(59, 'Ethiopia', 'et', 'et.png');
INSERT INTO `Countries` VALUES(60, 'Faroe Islands', 'fo', 'fo.png');
INSERT INTO `Countries` VALUES(61, 'Fiji', 'fj', 'fj.png');
INSERT INTO `Countries` VALUES(62, 'Finland', 'fi', 'fi.png');
INSERT INTO `Countries` VALUES(63, 'France', 'fr', 'fr.png');
INSERT INTO `Countries` VALUES(64, 'Georgia', 'ge', 'ge.png');
INSERT INTO `Countries` VALUES(65, 'Germany', 'de', 'de.png');
INSERT INTO `Countries` VALUES(66, 'Ghana', 'gh', 'gh.png');
INSERT INTO `Countries` VALUES(67, 'United Kingdom', 'gb', 'gb.png');
INSERT INTO `Countries` VALUES(68, 'Greece', 'gr', 'gr.png');
INSERT INTO `Countries` VALUES(69, 'Greenland', 'gl', 'gl.png');
INSERT INTO `Countries` VALUES(70, 'Grenada', 'gd', 'gd.png');
INSERT INTO `Countries` VALUES(71, 'Guadaloupe', 'gp', 'gp.png');
INSERT INTO `Countries` VALUES(72, 'Guam', 'gu', 'gu.png');
INSERT INTO `Countries` VALUES(73, 'Guatemala', 'gt', 'gt.png');
INSERT INTO `Countries` VALUES(74, 'Guinea', 'gn', 'gn.png');
INSERT INTO `Countries` VALUES(75, 'Guyana', 'gy', 'gy.png');
INSERT INTO `Countries` VALUES(76, 'Haiti', 'ht', 'ht.png');
INSERT INTO `Countries` VALUES(77, 'Honduras', 'hn', 'hn.png');
INSERT INTO `Countries` VALUES(78, 'Hong Kong', 'hk', 'hk.png');
INSERT INTO `Countries` VALUES(79, 'Hungary', 'hu', 'hu.png');
INSERT INTO `Countries` VALUES(80, 'Iceland', 'is', 'is.png');
INSERT INTO `Countries` VALUES(81, 'India', 'in', 'in.png');
INSERT INTO `Countries` VALUES(82, 'Indonesia', 'id', 'id.png');
INSERT INTO `Countries` VALUES(83, 'Iran', 'ia', 'ia.png');
INSERT INTO `Countries` VALUES(84, 'Iraq', 'iq', 'iq.png');
INSERT INTO `Countries` VALUES(85, 'Ireland', 'ir', 'ir.png');
INSERT INTO `Countries` VALUES(86, 'Israel', 'il', 'il.png');
INSERT INTO `Countries` VALUES(87, 'Italy', 'it', 'it.png');
INSERT INTO `Countries` VALUES(88, 'Jamaica', 'jm', 'jm.png');
INSERT INTO `Countries` VALUES(89, 'Japan', 'jp', 'jp.png');
INSERT INTO `Countries` VALUES(90, 'Jordan', 'jo', 'jo.png');
INSERT INTO `Countries` VALUES(91, 'Kazakhstan', 'kz', 'kz.png');
INSERT INTO `Countries` VALUES(92, 'Kenya', 'ke', 'ke.png');
INSERT INTO `Countries` VALUES(93, 'Kiribati', 'ki', 'ki.png');
INSERT INTO `Countries` VALUES(94, 'Korea', 'kr', 'kr.png');
INSERT INTO `Countries` VALUES(95, 'Kuwait', 'kw', 'kw.png');
INSERT INTO `Countries` VALUES(96, 'Kyrgyzstan', 'kg', 'kg.png');
INSERT INTO `Countries` VALUES(97, 'Laos', 'la', 'la.png');
INSERT INTO `Countries` VALUES(98, 'Latvia', 'lv', 'lv.png');
INSERT INTO `Countries` VALUES(99, 'Lebanon', 'lb', 'lb.png');
INSERT INTO `Countries` VALUES(100, 'Liberia', 'lr', 'lr.png');
INSERT INTO `Countries` VALUES(101, 'Liechtenstein', 'li', 'li.png');
INSERT INTO `Countries` VALUES(102, 'Luxembourg', 'lu', 'lu.png');
INSERT INTO `Countries` VALUES(103, 'Lybia', 'ly', 'ly.png');
INSERT INTO `Countries` VALUES(104, 'Macedonia', 'mk', 'mk.png');
INSERT INTO `Countries` VALUES(105, 'Malaysia', 'my', 'my.png');
INSERT INTO `Countries` VALUES(106, 'Mali', 'ml', 'ml.png');
INSERT INTO `Countries` VALUES(107, 'Malta', 'mt', 'mt.png');
INSERT INTO `Countries` VALUES(108, 'Mexico', 'mx', 'mx.png');
INSERT INTO `Countries` VALUES(109, 'Moldova', 'md', 'md.png');
INSERT INTO `Countries` VALUES(110, 'Myanmar', 'mn', 'mn.png');
INSERT INTO `Countries` VALUES(111, 'Morocco', 'ma', 'ma.png');
INSERT INTO `Countries` VALUES(112, 'Mozambique', 'mz', 'mz.png');
INSERT INTO `Countries` VALUES(113, 'Namibia', 'na', 'na.png');
INSERT INTO `Countries` VALUES(114, 'Nauru', 'nu', 'nu.png');
INSERT INTO `Countries` VALUES(115, 'Nepal', 'np', 'np.png');
INSERT INTO `Countries` VALUES(116, 'Netherlands', 'nl', 'nl.png');
INSERT INTO `Countries` VALUES(117, 'New Zealand', 'nz', 'nz.png');
INSERT INTO `Countries` VALUES(118, 'Nicaragua', 'ni', 'ni.png');
INSERT INTO `Countries` VALUES(119, 'Niger', 'ne', 'ne.png');
INSERT INTO `Countries` VALUES(120, 'Nigeria', 'ng', 'ng.png');
INSERT INTO `Countries` VALUES(121, 'Norway', 'no', 'no.png');
INSERT INTO `Countries` VALUES(122, 'Oman', 'om', 'om.png');
INSERT INTO `Countries` VALUES(123, 'Pakistan', 'pk', 'pk.png');
INSERT INTO `Countries` VALUES(124, 'Panama', 'pa', 'pa.png');
INSERT INTO `Countries` VALUES(125, 'Paraguay', 'py', 'py.png');
INSERT INTO `Countries` VALUES(126, 'Peru', 'pe', 'pe.png');
INSERT INTO `Countries` VALUES(127, 'Philippines', 'ph', 'ph.png');
INSERT INTO `Countries` VALUES(128, 'Poland', 'pl', 'pl.png');
INSERT INTO `Countries` VALUES(129, 'Portugal', 'pt', 'pt.png');
INSERT INTO `Countries` VALUES(130, 'Puerto Rico', 'pr', 'pr.png');
INSERT INTO `Countries` VALUES(131, 'Qatar', 'qa', 'qa.png');
INSERT INTO `Countries` VALUES(132, 'Romania', 'ro', 'ro.png');
INSERT INTO `Countries` VALUES(133, 'Russia', 'ru', 'ru.png');
INSERT INTO `Countries` VALUES(134, 'Rwanda', 'rw', 'rw.png');
INSERT INTO `Countries` VALUES(135, 'St Lucia', 'lc', 'lc.png');
INSERT INTO `Countries` VALUES(136, 'San Marino', 'sm', 'sm.png');
INSERT INTO `Countries` VALUES(137, 'Saudi Arabia', 'sa', 'sa.png');
INSERT INTO `Countries` VALUES(138, 'Senegal', 'sn', 'sn.png');
INSERT INTO `Countries` VALUES(139, 'Serbia - Montenegro', 'ss', 'ss.png');
INSERT INTO `Countries` VALUES(140, 'Singapore', 'sg', 'sg.png');
INSERT INTO `Countries` VALUES(141, 'Slovakia', 'sk', 'sk.png');
INSERT INTO `Countries` VALUES(142, 'Slovenia', 'si', 'si.png');
INSERT INTO `Countries` VALUES(143, 'Somalia', 'so', 'so.png');
INSERT INTO `Countries` VALUES(144, 'Zimbawe', 'za', 'za.png');
INSERT INTO `Countries` VALUES(145, 'Spain', 'es', 'es.png');
INSERT INTO `Countries` VALUES(146, 'Sudan', 'sd', 'sd.png');
INSERT INTO `Countries` VALUES(147, 'Suriname', 'sr', 'sr.png');
INSERT INTO `Countries` VALUES(148, 'Sweden', 'se', 'se.png');
INSERT INTO `Countries` VALUES(149, 'Switzerland', 'ch', 'ch.png');
INSERT INTO `Countries` VALUES(150, 'Syria', 'sy', 'sy.png');
INSERT INTO `Countries` VALUES(151, 'Taiwan', 'tw', 'tw.png');
INSERT INTO `Countries` VALUES(152, 'Thailand', 'th', 'th.png');
INSERT INTO `Countries` VALUES(153, 'Togo', 'tg', 'tg.png');
INSERT INTO `Countries` VALUES(154, 'Tokelau', 'tk', 'tk.png');
INSERT INTO `Countries` VALUES(155, 'Tonga', 'to', 'to.png');
INSERT INTO `Countries` VALUES(156, 'Tridinidad Tobago', 'tt', 'tt.png');
INSERT INTO `Countries` VALUES(157, 'Tunisia', 'tn', 'tn.png');
INSERT INTO `Countries` VALUES(158, 'Turkey', 'tr', 'tr.png');
INSERT INTO `Countries` VALUES(159, 'Ukraine', 'ua', 'ua.png');
INSERT INTO `Countries` VALUES(160, 'United Arab Emirate', 'ae', 'ae.png');
INSERT INTO `Countries` VALUES(161, 'United States', 'us', 'us.png');
INSERT INTO `Countries` VALUES(162, 'Uruguay', 'uy', 'uy.png');
INSERT INTO `Countries` VALUES(163, 'Vatican', 'va', 'va.png');
INSERT INTO `Countries` VALUES(164, 'Venezuela', 've', 've.png');
INSERT INTO `Countries` VALUES(165, 'Vietnam', 'vn', 'vn.png');
